/*
 * Transposh v0.9.9.1
 * http://transposh.org/
 *
 * Copyright 2016, Team Transposh
 * Licensed under the GPL Version 2 or higher.
 * http://transposh.org/license
 *
 * Date: Sun, 15 May 2016 11:33:49 +0300
 */
(function(c){function B(b,a){if(0!==c.trim(a).length){var d=function(){var b=c(this).attr("id").substr(c(this).attr("id").lastIndexOf("_")+1),d=c("#"+f+"img_"+b);c("#"+f+b).attr("data-source",1);d.removeClass("tr-icon-yellow").removeClass("tr-icon-green").addClass("tr-icon-yellow")};b=b.replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g,"\\$1");c("*[data-orig='"+b+"'][data-hidden!='y']").html(a).each(d);c("*[data-orig='"+b+"'][data-hidden='y']").attr("data-trans",a).each(d)}}function C(b,a){clearTimeout(s);
h.push(b);p.push(a);B(b,a);s=setTimeout(function(){var b={ln0:t_jp.lang,sr0:l,action:"tp_translation",items:h.length},a;for(a=0;a<h.length;a+=1)b["tk"+a]=h[a],b["tr"+a]=p[a],q+=c("*[data-orig='"+h[a].replace(/([;&,\.\+\*\~':"\!\^#$%@\[\]\(\)=>\|])/g,"\\$1")+"']").size();c.ajax({type:"POST",url:t_jp.ajaxurl,data:b,success:function(){console.window&&console.log(q+"/"+m+" translations posted")}});p=[];h=[]},200)}function k(b,a){C(b,c("<div>"+c.trim(a)+"</div>").text());window.console&&console.log(m-
c("."+f+'[data-source=""]').size()+"/"+m+" auto translated")}function t(b,a,d){c.ajax({url:t_jp.ajaxurl,dataType:"json",type:"GET",data:{action:"tp_tp",e:"g",tl:d,q:b},success:a})}function D(b,a){t(a,function(a){c(a.results).each(function(a){k(b[a],this)})},t_jp.lang)}function n(b,a,d){if(t_jp.msn_key){var e="[";c(b).each(function(a){e+='"'+encodeURIComponent(b[a].replace(/[\\"]/g,"\\$&").replace(/(\r\n|\n|\r)/gm," "))+'",'});e=e.slice(0,-1)+"]";c.ajax({url:"//api.microsofttranslator.com/V2/Ajax.svc/TranslateArray?appId="+
t_jp.msn_key+"&to="+d+"&texts="+e,dataType:"jsonp",jsonp:"oncomplete",success:a})}else 1===u?setTimeout(function(){n(b,a,d)},500):(u=1,c.getScript("//www.microsofttranslator.com/ajax/v2/toolkit.ashx?loc=en&toolbar=none",function(){t_jp.msn_key=_mstConfig.appId;n(b,a,d)}))}function E(b,a){l=2;n(a,function(a){c(a).each(function(a){k(b[a],this.TranslatedText)})},t_jp.blang)}function v(b,a,d){c.ajax({url:t_jp.ajaxurl,dataType:"json",type:"GET",data:{action:"tp_tp",e:"y",tl:d,q:b},success:a})}function F(b,
a){l=4;v(a,function(a){c(a.results).each(function(a){k(b[a],this)})},t_jp.lang)}function w(b,a,d){c.ajax({url:t_jp.ajaxurl,dataType:"json",type:"GET",data:{action:"tp_tp",e:"u",tl:d,q:b},success:a})}function G(b,a){l=5;w(a,function(a){c(a.results).each(function(a){k(b[a],this)})},t_jp.lang)}function x(b,a,d){c.ajax({url:"http://api.apertium.org/json/translate",data:{q:b,langpair:t_jp.olang+"|"+d,markUnknown:"no"},dataType:"jsonp",traditional:!0,success:a})}function H(b,a){l=3;x(a,function(a){200<=
a.responseStatus&&300>a.responseStatus&&(void 0!==a.responseData.translatedText?k(b[0],a.responseData.translatedText):c(a.responseData).each(function(a){200===this.responseStatus&&k(b[a],this.responseData.translatedText)}))},t_jp.lang)}function y(b,a){t_jp.preferred.some(function(c){if(t_jp.engines[c])return"a"===c&&H(b,a),"b"===c&&E(b,a),"g"===c&&D(b,a),"y"===c&&F(b,a),"u"===c&&G(b,a),!0})}function z(){var b=[],a=0,d=[],e=[];c("."+f+'[data-source=""]').each(function(){var f=c(this).attr("data-orig"),
g=c(this).attr("data-orig");void 0===g&&(g=c(this).html());1!==b[g]&&(b[g]=1,a+encodeURIComponent(g).length>I&&(y(e,d),a=0,d=[],e=[]),a+=encodeURIComponent(g).length,e.push(f),d.push(g))});y(e,d)}function A(b){"function"===typeof c.xLazyLoader?b():(t_jp.$=c,c.getScript(t_jp.plugin_url+"/js/lazy.js",b).done(b))}function r(b){r.hit?b():(r.hit=!0,A(function(){c.fn.propAttr=c.fn.prop||c.fn.attr;c.xLazyLoader({js:t_jp.jQueryUI+"jquery-ui.min.js",css:t_jp.jQueryUI+"themes/"+t_jp.theme+"/jquery-ui.css",
success:b})}))}var I=1024,m,f=t_jp.prefix,l=1,q=0,s,h=[],p=[],u=0;t_jp.dgpt=t;t_jp.dbt=n;t_jp.dyt=v;t_jp.dut=w;t_jp.dat=x;t_jp.at=z;t_jp.tfl=A;t_jp.tfju=r;c(function(){"undefined"===typeof t_jp.blang&&(t_jp.blang=t_jp.lang);c("."+f+"setdeflang").click(function(){c.ajax({url:t_jp.ajaxurl,data:{action:"tp_cookie"},cache:!1});c("."+f+"setdeflang").hide("slow");return!1});m=c("."+f+'[data-source=""]').size();c.ajaxSetup({cache:!0});!m||t_jp.noauto||c.isEmptyObject(t_jp.engines)||z();t_jp.edit&&c.getScript(t_jp.plugin_url+
"/js/transposhedit.js")})})(jQuery);
